baseURL = "https://test-ventoux-coop.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Ventoux Coop"
[markup.goldmark.renderer]
unsafe = true
