baseURL = "https://laughing-villani-67633b.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Bigspring Hugo"
[markup.goldmark.renderer]
unsafe = true
